services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./content:/app/content:z
      - ./data:/app/data:z
      - ./static:/app/static:z
    env_file:
      - ./.envs/.production/.fastapi
      - ./.envs/.production/.postgres

  caddy:
    image: caddy:2.7.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.envs/.production/.caddy
    volumes:
      - ./compose/production/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - sni_postgres_data:/var/lib/postgresql/data
      - sni_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    healthcheck:
      test: ["CMD-ONLY", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  sni_postgres_data: {}
  sni_postgres_data_backups: {}
